### ISSUE TITLE
Progresso da tradução

### ISSUE THREAD

**Issue by lbighetti** [lbighetti/guia.elm-lang.pt#23]
- [x] [About this translation](about_translation.md) - #1 
- [x] [Introduction](README.md) - #1
- [x] [Install](install.md) - #11 
- [x] [Core Language](core_language.md) - #10 
- [ ] [The Elm Architecture](architecture/README.md) - #14 
   - [x] [Buttons](architecture/buttons.md) - #12 
   - [x] [Text Fields](architecture/text_fields.md) - #13 
   - [ ] [Forms](architecture/forms.md)
- [ ] [Types](types/README.md)
   - [ ] [Reading Types](types/reading_types.md)
   - [ ] [Type Aliases](types/type_aliases.md)
   - [ ] [Custom Types](types/custom_types.md)
   - [ ] [Pattern Matching](types/pattern_matching.md)
- [ ] [Error Handling](error_handling/README.md)
   - [ ] [Maybe](error_handling/maybe.md)
   - [ ] [Result](error_handling/result.md)
- [ ] [Commands and Subscriptions](effects/README.md)
   - [ ] [HTTP](effects/http.md)
   - [ ] [JSON](effects/json.md)
   - [ ] [Random](effects/random.md)
   - [ ] [Time](effects/time.md)
- [ ] [JavaScript Interop](interop/README.md)
   - [ ] [Flags](interop/flags.md)
   - [ ] [Ports](interop/ports.md)
   - [ ] [Custom Elements](interop/custom_elements.md)
- [ ] [Web Apps](webapps/README.md)
   - [ ] [Navigation](webapps/navigation.md)
   - [ ] [URL Parsing](webapps/url_parsing.md)
   - [ ] [Modules](webapps/modules.md)
   - [ ] [Structure](webapps/structure.md)
- [ ] [Optimization](optimization/README.md)
   - [ ] [Html.lazy](optimization/lazy.md)
   - [ ] [Html.keyed](optimization/keyed.md)
   - [ ] [Minification](optimization/asset_size.md)
- [ ] [Next Steps](next_steps.md)
- [ ] Appendix
   - [ ] [Types as Sets](appendix/types_as_sets.md)
   - [ ] [Types as Bits](appendix/types_as_bits.md)
   - [ ] [Function Types](appendix/function_types.md)
